id = "kreonyx"
name = "KREONYX CLI"
description = "The open source coding agent."
version = "1.2.1"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/anomalyco/kreonyx"

[agent_servers.kreonyx]
name = "KREONYX CLI"
icon = "./icons/kreonyx.svg"

[agent_servers.kreonyx.targets.darwin-aarch64]
archive = "https://github.com/anomalyco/kreonyx/releases/download/v1.2.1/kreonyx-darwin-arm64.zip"
cmd = "./kreonyx"
args = ["acp"]

[agent_servers.kreonyx.targets.darwin-x86_64]
archive = "https://github.com/anomalyco/kreonyx/releases/download/v1.2.1/kreonyx-darwin-x64.zip"
cmd = "./kreonyx"
args = ["acp"]

[agent_servers.kreonyx.targets.linux-aarch64]
archive = "https://github.com/anomalyco/kreonyx/releases/download/v1.2.1/kreonyx-linux-arm64.tar.gz"
cmd = "./kreonyx"
args = ["acp"]

[agent_servers.kreonyx.targets.linux-x86_64]
archive = "https://github.com/anomalyco/kreonyx/releases/download/v1.2.1/kreonyx-linux-x64.tar.gz"
cmd = "./kreonyx"
args = ["acp"]

[agent_servers.kreonyx.targets.windows-x86_64]
archive = "https://github.com/anomalyco/kreonyx/releases/download/v1.2.1/kreonyx-windows-x64.zip"
cmd = "./kreonyx.exe"
args = ["acp"]
